In [3]:
import numpy as np

In [4]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(ar)

numpy.ndarray

In [6]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(2 * L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [12]:
2 * a + b

array([12, 24, 36])

In [13]:
a == 2

array([False,  True, False])

In [14]:
b > 10

array([False,  True,  True])

In [15]:
(a == 2) & (b > 10)

array([False,  True, False])

In [16]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
# 행의 갯수
len(c)

2

In [18]:
# 열의 갯수
len(c[0])

3

In [19]:
# 3.1 넘파이 배열 연습 문제 1
c = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])  # 2 x 3 array
c

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [20]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [21]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [22]:
# a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [23]:
c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [24]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [25]:
a = np.array([0, 1, 2, 3, 4])

In [26]:
a[2]

2

In [27]:
a[-1]

4

In [28]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
a[0, 0]  # 첫번째 행의 첫번째 열

0

In [30]:
a[0, 1]  # 첫번째 행의 두번째 열

1

In [31]:
a[-1, -1]  # 마지막 행의 마지막 열

5

In [32]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [33]:
a[0, :]  # 첫번째 행 전체

array([0, 1, 2, 3])

In [34]:
a[:, 1]  # 두번째 열 전체

array([1, 5])

In [35]:
a[1, 1:]  # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [36]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [37]:
# 3.1 넘파이 배열 연습 문제 2
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
# 이 행렬에서 값 7 을 인덱싱한다.
# m[1, 2]
# 이 행렬에서 값 14 을 인덱싱한다.
# m[-1, -1]
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
# m[1, 1:3]
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
# [m[1, 2], m[2, 2]] , m[1:3, 2:3]
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
# m[:2, 3:]

In [38]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [39]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [40]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [41]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [42]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [43]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [44]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [46]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [47]:
# 3.1 넘파이 배열 연습 문제 3
# 다음 행렬과 같은 배열이 있다.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 이 배열에서 3의 배수를 찾아라.
# x[x % 3 == 0]
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
# x[x % 4 == 1]
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
# x[(x % 3 == 0) & (x % 4 == 1)]

In [48]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [49]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [50]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [51]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [52]:
x[0] + x[1]

3.0

In [53]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [54]:
x[0] + x[1]

'12'

In [55]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\박랑희\AppData\Local\Temp\ipykernel_145132\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\박랑희\AppData\Local\Temp\ipykernel_145132\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [56]:
np.log(0)

C:\Users\박랑희\AppData\Local\Temp\ipykernel_145132\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [57]:
np.exp(-np.inf)

0.0

In [58]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [59]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
c = np.zeros((5, 2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [61]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [62]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [63]:
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [64]:
f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [65]:
g = np.empty((4, 3))
g

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313],
       [2.54639495e-313, 2.97079411e-313, 3.39519327e-313],
       [3.81959242e-313, 4.24399158e-313, 4.66839074e-313]])

In [66]:
np.arange(10)  # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.arange(3, 21, 2)  # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [68]:
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [69]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [70]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [76]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [77]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [80]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [81]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [82]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [83]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [84]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [85]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [86]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [87]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [90]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [92]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [93]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [94]:
c.shape

(2, 3, 4)

In [95]:
c = np.stack([c1, c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [96]:
c.shape

(3, 2, 4)

In [97]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [98]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [99]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [100]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [101]:
# 3.2 배열의 생성과 변형 연습 문제 1
# 지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.
a = np.r_[np.zeros(3), np.ones(2)]
b = np.tile(a, (3,1))
c = np.linspace(10, 150, 15).reshape(-1, 5)
d = np.vstack([b, c])
e = np.tile(d, (2,1))
e

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [102]:
x = np.arange(3)
x

array([0, 1, 2])

In [103]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [104]:
X, Y = np.meshgrid(x, y)

In [105]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [106]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [107]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [108]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [109]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: total: 0 ns
Wall time: 3.1 ms


In [110]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [111]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [112]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [113]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [114]:
a == b

array([False,  True, False,  True])

In [115]:
a >= b

array([False,  True,  True,  True])

In [116]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [117]:
np.all(a == b)

False

In [118]:
np.all(a == c)

True

In [119]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [120]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [121]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [122]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [123]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [125]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [127]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [128]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [129]:
x + y

array([1, 2, 3, 4, 5])

In [130]:
x + 1

array([1, 2, 3, 4, 5])

In [131]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [132]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [133]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [134]:
y = np.arange(3)
y

array([0, 1, 2])

In [135]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [136]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [137]:
np.sum(x)

10

In [138]:
x.sum()

10

In [139]:
x = np.array([1, 3, 2])

In [140]:
x.min()

1

In [141]:
x.max()

3

In [142]:
x.argmin()  # 최솟값의 위치

0

In [143]:
x.argmax()  # 최댓값의 위치

1

In [144]:
x = np.array([1, 2, 3, 1])

In [145]:
x.mean()

1.75

In [146]:
np.median(x)

1.5

In [147]:
np.all([True, True, False])

False

In [148]:
np.any([True, True, False])

True

In [149]:
a = np.zeros((100, 100), dtype=np.int32)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [150]:
np.any(a != 0)

False

In [151]:
np.all(a == a)

True

In [152]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [153]:
((a <= b) & (b <= c)).all()

True

In [154]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [155]:
x.sum()

6

In [156]:
x.sum(axis=0)   # 열 합계

array([3, 3])

In [157]:
x.sum(axis=1)   # 행 합계

array([2, 4])

In [158]:
# 3.3 배열의 연산 연습 문제 1
# 실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

x = np.vstack([range(30)[i:i+6] for i in range(5)])
x
# 전체의 최댓값
# x.max()
# 각 행의 합
# x.sum(axis=1)
# 각 행의 최댓값
# x.max(axis=1)
# 각 열의 평균
# x.mean(axis=0)
# 각 열의 최솟값
# x.min(axis=0)

array([[0, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 9]])

In [159]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [160]:
np.sort(a)  # axis=-1 또는 axis=1 과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [161]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [162]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [163]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [164]:
a[j]

array([12, 25, 38, 42])

In [165]:
np.sort(a)

array([12, 25, 38, 42])

In [166]:
# 3.3 배열의 연산 연습 문제 2
# 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.
v = np.array([[  1,    2,    3,    4],
              [ 46,   99,  100,   71],
              [ 81,   59,   90,  100]])
a = np.argsort(v[1]) # 두번째 행(인덱스: 1)을 순서로만 정렬
v[:, a] # 두번째 행을 기준으로 전체 열을 순서 재정렬

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [167]:
# 3.3 배열의 연산 연습 문제 2 (정답2)
v[:, np.argsort(v[1])]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [168]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [169]:
len(x)  # 갯수

26

In [170]:
np.mean(x)  # 평균

4.8076923076923075

In [171]:
np.var(x)  # 분산

115.23224852071006

In [172]:
np.var(x, ddof=1)  # 비편향 분산. 추후 공부하게 된다.

119.84153846153846

In [173]:
np.std(x)  # 표준 편차

10.734628476137871

In [174]:
np.max(x)  # 최댓값

23

In [175]:
np.min(x)  # 최솟값

-24

In [176]:
np.median(x)  # 중앙값

5.0

In [177]:
np.percentile(x, 0)  # 최소값

-24.0

In [178]:
np.percentile(x, 25)  # 1사분위 수

0.0

In [179]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [180]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [181]:
np.percentile(x, 100)  # 최댓값

23.0

In [182]:
np.random.seed(0)

In [183]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [184]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [185]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [186]:
np.random.seed(0)

In [187]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [188]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [189]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [190]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
np.random.shuffle(x)
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

In [192]:
np.random.choice(5, 5, replace=False)  # shuffle 명령과 같다.

array([1, 4, 0, 3, 2])

In [193]:
np.random.choice(5, 3, replace=False)  # 3개만 선택

array([2, 1, 3])

In [194]:
np.random.choice(5, 10)  # 반복해서 10개 선택

array([0, 4, 1, 4, 1, 2, 2, 0, 1, 1])

In [195]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택

array([0, 3, 3, 2, 2, 3, 3, 2, 0, 3])

In [196]:
np.random.rand(10)

array([0.95894927, 0.65279032, 0.63505887, 0.99529957, 0.58185033,
       0.41436859, 0.4746975 , 0.6235101 , 0.33800761, 0.67475232])

In [197]:
np.random.rand(3, 5)

array([[0.31720174, 0.77834548, 0.94957105, 0.66252687, 0.01357164],
       [0.6228461 , 0.67365963, 0.971945  , 0.87819347, 0.50962438],
       [0.05571469, 0.45115921, 0.01998767, 0.44171092, 0.97958673]])

In [198]:
np.random.randn(10)

array([-0.30237513, -2.2244036 ,  0.72400636,  0.35900276,  1.07612104,
        0.19214083,  0.85292596,  0.01835718,  0.42830357,  0.99627783])

In [199]:
np.random.randn(3, 5)

array([[-0.49114966,  0.71267817,  1.11334035, -2.15367459, -0.41611148],
       [-1.07089699,  0.22113881, -1.12305712, -1.05075796,  1.01207905],
       [ 1.54371643, -0.40211489,  0.8647491 , -0.22686923,  0.81116027]])

In [200]:
np.random.randint(10, size=10)

array([0, 4, 3, 6, 9, 8, 0, 8, 5, 9])

In [201]:
np.random.randint(10, 20, size=10)

array([10, 19, 16, 15, 13, 11, 18, 10, 14, 19])

In [202]:
np.random.randint(10, 20, size=(3, 5))

array([[16, 15, 17, 18, 18],
       [19, 12, 18, 16, 16],
       [19, 11, 16, 18, 18]])

In [203]:
# 3.5 난수 발생과 카운팅 연습 문제 1
# 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
c = np.random.choice(2, 10, p=[0.5, 0.5])
c
# 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
a = np.random.randint(7, size=100)
a.mean()

3.12

In [268]:
# 3.5 난수 발생과 카운팅 연습 문제 2
# 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라.
n = 10000
x = np.random.randn(250)
for i in x:
    n = n * (1 + (i / 100))
print("{:,}원".format(round(n)))

10,541원


In [270]:
# 3.5 난수 발생과 카운팅 연습 문제 2 (정답 2)
# R/100 = 수익률 , price = 주가
R = np.random.randn(250)
stock = []
for i in range(250):
    price = 10000
    price = price * (R[i]/100 + 1)
    stock.append(price)
    stock[i] = round(stock[i],2)
stock = np.array(stock)
print(stock)
# print("{:,}원".format(round(stock)))

[10067.1  10052.02  9744.09  9921.21 10248.17  9988.83 10015.34  9963.18
 10055.93  9971.13  9908.05 10107.   10034.31  9948.69 10169.55 10124.6
  9992.39 10028.8   9674.6  10047.92 10013.1  10047.11 10020.33 10122.55
 10035.56  9974.75  9881.    9956.5   9950.12  9984.94  9962.75 10001.88
 10110.16 10086.74 10034.84  9845.04 10054.48 10021.75 10122.34  9971.79
 10053.64 10064.64 10097.31  9913.95 10080.87 10078.45 10030.97 10036.33
 10043.87  9986.34  9997.35  9911.04  9979.15  9946.94 10097.26  9825.81
 10037.04  9948.1   9962.34 10020.3  10078.61  9895.3   9900.8  10074.55
  9813.07  9998.08  9828.49 10054.17  9999.73  9934.28  9970.78 10040.69
  9923.47 10002.13 10012.29  9967.86  9861.38 10168.09  9883.02  9994.8
  9932.01 10141.51  9992.59  9886.17 10028.95 10088.58 10075.44 10054.35
 10116.41  9971.13 10211.45 10065.63  9978.94 10032.3   9927.28  9932.68
  9979.88  9928.29 10022.56  9982.3  10019.36 10018.47  9953.07 10184.61
 10069.12  9876.99  9969.14 10286.47 10024.93  9930.9

In [271]:
# 3.5 난수 발생과 카운팅 연습 문제 2 (정답 3)
R = np.random.randn(250)
stock = []
price = 10000
for i in range(250):
    price = price * (R[i]/100 + 1)
    stock.append(int(price))
    
stock = np.array(stock)
print(stock)

[ 9971 10258 10157 10016 10125 10200 10047 10003  9947  9940 10011 10048
  9918 10190 10226 10002 10090 10185 10130 10132 10158 10031  9989 10053
  9892  9929  9959 10002 10033 10163 10130 10040  9982  9817  9911  9848
  9824  9795  9816 10084  9984 10065 10170 10306 10327 10467 10423 10458
 10531 10662 10588 10536 10574 10819 10771 10813 10653 10629 10679 10607
 10464 10571 10552 10505 10481 10527 10538 10522 10327 10368 10467 10510
 10255 10208 10312 10253 10158 10118 10058  9941  9988 10106 10041 10118
 10033  9889  9878  9981 10013 10286 10236 10128 10061 10067 10108 10282
 10466 10789 10988 11128 11147 11140 11025 10977 11125 11049 11286 11203
 11425 11368 11605 11488 11371 11347 11382 11525 11479 11452 11279 11053
 11101 11058 11083 11107 11096 10831 10914 10927 10807 10822 10775 10586
 10735 10840 10750 10547 10738 10773 10736 10537 10482 10230 10241 10497
 10570 10760 10857 10879 10888 10948 10980 10929 10878 11018 11075 11028
 11034 10873 10907 10919 10932 10846 10739 10777 10

In [205]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [206]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [207]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [208]:
count

array([2, 2, 1], dtype=int64)

In [209]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)