In [161]:
import numpy as np

In [162]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
type(ar)

numpy.ndarray

In [164]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [165]:
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [166]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [168]:
L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(2 * L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [169]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [170]:
2 * a + b

array([12, 24, 36])

In [171]:
a == 2

array([False,  True, False])

In [172]:
b > 10

array([False,  True,  True])

In [173]:
(a == 2) & (b > 10)

array([False,  True, False])

In [174]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [175]:
# 행의 갯수
len(c)

2

In [176]:
# 열의 갯수
len(c[0])

3

In [177]:
# 3.1 넘파이 배열 연습 문제 1
c = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])  # 2 x 3 array
c

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [178]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [179]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [180]:
# a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [181]:
c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [182]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [183]:
a = np.array([0, 1, 2, 3, 4])

In [184]:
a[2]

2

In [185]:
a[-1]

4

In [186]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [187]:
a[0, 0]  # 첫번째 행의 첫번째 열

0

In [188]:
a[0, 1]  # 첫번째 행의 두번째 열

1

In [189]:
a[-1, -1]  # 마지막 행의 마지막 열

5

In [190]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [191]:
a[0, :]  # 첫번째 행 전체

array([0, 1, 2, 3])

In [192]:
a[:, 1]  # 두번째 열 전체

array([1, 5])

In [193]:
a[1, 1:]  # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [194]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [195]:
# 3.1 넘파이 배열 연습 문제 2
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
# 이 행렬에서 값 7 을 인덱싱한다.
# m[1, 2]
# 이 행렬에서 값 14 을 인덱싱한다.
# m[-1, -1]
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
# m[1, 1:3]
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
# [m[1, 2], m[2, 2]] , m[1:3, 2:3]
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
# m[:2, 3:]

In [196]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [197]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [198]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [199]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [200]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [201]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [202]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [203]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [204]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [205]:
# 3.1 넘파이 배열 연습 문제 3
# 다음 행렬과 같은 배열이 있다.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 이 배열에서 3의 배수를 찾아라.
# x[x % 3 == 0]
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
# x[x % 4 == 1]
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
# x[(x % 3 == 0) & (x % 4 == 1)]

In [206]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [207]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [208]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [209]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [210]:
x[0] + x[1]

3.0

In [211]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [212]:
x[0] + x[1]

'12'

In [213]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\박랑희\AppData\Local\Temp\ipykernel_105712\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\박랑희\AppData\Local\Temp\ipykernel_105712\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [214]:
np.log(0)

C:\Users\박랑희\AppData\Local\Temp\ipykernel_105712\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [215]:
np.exp(-np.inf)

0.0

In [216]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [217]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [218]:
c = np.zeros((5, 2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [219]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [220]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [221]:
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [222]:
f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [223]:
g = np.empty((4, 3))
g

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313],
       [2.54639495e-313, 2.97079411e-313, 3.39519327e-313],
       [3.81959242e-313, 4.24399158e-313, 4.66839074e-313]])

In [224]:
np.arange(10)  # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [225]:
np.arange(3, 21, 2)  # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [226]:
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [227]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [228]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [229]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [230]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [231]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [232]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [233]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [234]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [235]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [236]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [237]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [238]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [239]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [240]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [241]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [242]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [243]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [244]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [245]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [246]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [247]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [248]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [249]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [250]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [251]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [252]:
c.shape

(2, 3, 4)

In [253]:
c = np.stack([c1, c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [254]:
c.shape

(3, 2, 4)

In [255]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [256]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [257]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [258]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [259]:
# 3.2 배열의 생성과 변형 연습 문제 1
# 지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.
a = np.r_[np.zeros(3), np.ones(2)]
b = np.tile(a, (3,1))
c = np.linspace(10, 150, 15).reshape(-1, 5)
d = np.vstack([b, c])
e = np.tile(d, (2,1))
e

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [260]:
x = np.arange(3)
x

array([0, 1, 2])

In [261]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [262]:
X, Y = np.meshgrid(x, y)

In [263]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [264]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [265]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [266]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [267]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: total: 0 ns
Wall time: 2 ms


In [268]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [269]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [270]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [271]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [272]:
a == b

array([False,  True, False,  True])

In [273]:
a >= b

array([False,  True,  True,  True])

In [274]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [275]:
np.all(a == b)

False

In [276]:
np.all(a == c)

True

In [277]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [278]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [279]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [280]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [281]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [282]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [283]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [284]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [285]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [286]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [287]:
x + y

array([1, 2, 3, 4, 5])

In [288]:
x + 1

array([1, 2, 3, 4, 5])

In [289]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [290]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [291]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [292]:
y = np.arange(3)
y

array([0, 1, 2])

In [293]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [294]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [295]:
np.sum(x)

10

In [296]:
x.sum()

10

In [297]:
x = np.array([1, 3, 2])

In [298]:
x.min()

1

In [299]:
x.max()

3

In [300]:
x.argmin()  # 최솟값의 위치

0

In [301]:
x.argmax()  # 최댓값의 위치

1

In [302]:
x = np.array([1, 2, 3, 1])

In [303]:
x.mean()

1.75

In [304]:
np.median(x)

1.5

In [305]:
np.all([True, True, False])

False

In [306]:
np.any([True, True, False])

True

In [317]:
a = np.zeros((100, 100), dtype=np.int32)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [319]:
np.any(a != 0)

False

In [320]:
np.all(a == a)

True

In [321]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [322]:
((a <= b) & (b <= c)).all()

True

In [323]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [324]:
x.sum()

6

In [325]:
x.sum(axis=0)   # 열 합계

array([3, 3])

In [327]:
x.sum(axis=1)   # 행 합계

array([2, 4])

In [375]:
# 3.3 배열의 연산 연습 문제 1
# 실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

x = np.vstack([range(30)[i:i+6] for i in range(5)])
x
# 전체의 최댓값
# x.max()
# 각 행의 합
# x.sum(axis=1)
# 각 행의 최댓값
# x.max(axis=1)
# 각 열의 평균
# x.mean(axis=0)
# 각 열의 최솟값
# x.min(axis=0)

array([[0, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 9]])

In [376]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [377]:
np.sort(a)  # axis=-1 또는 axis=1 과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [378]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [379]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [380]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [381]:
a[j]

array([12, 25, 38, 42])

In [382]:
np.sort(a)

array([12, 25, 38, 42])

In [406]:
# 3.3 배열의 연산 연습 문제 2
# 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.
v = np.array([[  1,    2,    3,    4],
              [ 46,   99,  100,   71],
              [ 81,   59,   90,  100]])
a = np.argsort(v[1]) # 두번째 행(인덱스: 1)을 순서로만 정렬
v[:, a] # 두번째 행을 기준으로 전체 열을 순서 재정렬

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [407]:
# 3.3 배열의 연산 연습 문제 2 (정답2)
v[:, np.argsort(v[1])]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [408]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [409]:
len(x)  # 갯수

26

In [410]:
np.mean(x)  # 평균

4.8076923076923075

In [411]:
np.var(x)  # 분산

115.23224852071006

In [412]:
np.var(x, ddof=1)  # 비편향 분산. 추후 공부하게 된다.

119.84153846153846

In [413]:
np.std(x)  # 표준 편차

10.734628476137871

In [414]:
np.max(x)  # 최댓값

23

In [415]:
np.min(x)  # 최솟값

-24

In [416]:
np.median(x)  # 중앙값

5.0

In [417]:
np.percentile(x, 0)  # 최소값

-24.0

In [418]:
np.percentile(x, 25)  # 1사분위 수

0.0

In [419]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [420]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [421]:
np.percentile(x, 100)  # 최댓값

23.0

In [422]:
np.random.seed(0)

In [423]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [424]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [425]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [426]:
np.random.seed(0)

In [427]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [428]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [429]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [443]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [519]:
np.random.shuffle(x)
x

array([5, 9, 4, 2, 3, 7, 1, 0, 6, 8])

In [520]:
np.random.choice(5, 5, replace=False)  # shuffle 명령과 같다.

array([1, 0, 2, 3, 4])

In [521]:
np.random.choice(5, 3, replace=False)  # 3개만 선택

array([2, 0, 3])

In [522]:
np.random.choice(5, 10)  # 반복해서 10개 선택

array([1, 4, 1, 4, 1, 2, 3, 2, 2, 2])

In [523]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택

array([3, 0, 3, 0, 2, 3, 2, 2, 2, 3])

In [524]:
np.random.rand(10)

array([0.69527001, 0.67195714, 0.94886102, 0.00270321, 0.64719665,
       0.60039224, 0.58873961, 0.96277032, 0.01687167, 0.69648243])

In [525]:
np.random.rand(3, 5)

array([[0.81367865, 0.5098072 , 0.33396487, 0.79084016, 0.09724293],
       [0.44203564, 0.51995237, 0.69395641, 0.09088573, 0.2277595 ],
       [0.41030156, 0.62329467, 0.88696078, 0.61882617, 0.13346147]])

In [526]:
np.random.randn(10)

array([ 0.82158571,  0.00529265,  0.8005648 ,  0.07826018, -0.39522898,
       -1.15942052, -0.08593077,  0.19429294,  0.87583276, -0.11510747])

In [527]:
np.random.randn(3, 5)

array([[ 0.45741561, -0.96461201, -0.78262916, -0.1103893 , -1.05462846],
       [ 0.82024784,  0.46313033,  0.27909576,  0.33890413,  2.02104356],
       [-0.46886419, -2.20144129,  0.1993002 , -0.05060354, -0.51751904]])

In [528]:
np.random.randint(10, size=10)

array([5, 0, 6, 8, 8, 6, 3, 4, 4, 3])

In [542]:
np.random.randint(10, 20, size=10)

array([19, 10, 17, 11, 12, 15, 10, 15, 18, 19])

In [545]:
np.random.randint(10, 20, size=(3, 5))

array([[15, 13, 13, 19, 14],
       [19, 10, 16, 15, 13],
       [10, 10, 11, 12, 10]])

In [553]:
# 3.5 난수 발생과 카운팅 연습 문제 1
# 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
c = np.random.choice(2, 10, p=[0.5, 0.5])
c
# 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
a = np.random.randint(7, size=100)
a.mean()

2.89

In [561]:
# 3.5 난수 발생과 카운팅 연습 문제 2
# 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라.
n = 10000
x = np.random.randn(250)
for i in x:
    n = n * (1 + (i / 100))
print("{:,}원".format(round(n)))

8,351원


In [562]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [563]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [564]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [565]:
count

array([2, 2, 1], dtype=int64)

In [566]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)